# Generated by Django 4.0.4 on 2022-06-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
