# Generated by Django 4.0.4 on 2022-06-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='avatar',
            field=models.ImageField(default='static/img/56854.png', upload_to=''),
        ),
    ]
