# Generated by Django 4.0.4 on 2022-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_question_answers_alter_question_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.png', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='avatar',
            field=models.ImageField(default='static/img/56854.png', upload_to='static/img/'),
        ),
    ]
