# Generated by Django 4.0.4 on 2022-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_avatar_alter_question_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.png', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='avatar',
            field=models.ImageField(default='static/img/56854.png', upload_to=''),
        ),
    ]
