# Generated by Django 4.0.4 on 2022-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.png', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
